### ISSUE TITLE
[백엔드] ERD 최신화

### ISSUE THREAD

**Issue by jimin3263** [ticket-together/ticket-server#117]
# 기능 설명
- [x] PPT에 추가하기 위해 수정된 ERD로 최신화

@younghyun-na @semi-cloud 
엔티티 코드 바탕으로 수정하였는데, 본인이 담당했던 도메인은 한 번씩 더 확인부탁드립니다@.@!!

https://www.erdcloud.com/d/7WLhk8YvAecWnn8dx

**Comment by younghyun-na** [comment]
review 부분은 확인했고 part 부분은 잘못된 부분 수정했습니당!

**Comment by jimin3263** [comment]
> review 부분은 확인했고 part 부분은 잘못된 부분 수정했습니당!

감쟈합니다!!! 🥔

**Comment by jimin3263** [comment]
@semi-cloud 

이 부분 완료되면 코멘트 부탁드립니다

**Comment by semi-cloud** [comment]
채팅 부분 완료했습니다!

**Comment by jimin3263** [comment]
> 채팅 부분 완료했습니다!

감쟈합니다!
