### ISSUE TITLE
[백엔드] 채팅 메시지 내용 검색

### ISSUE THREAD

**Issue by semi-cloud** [ticket-together/ticket-server#119]
# 기능 설명
- [ ] 채팅 메시지 내용 검색

**Comment by jimin3263** [comment]
@semi-cloud 

저희가 검색 기능, 푸시 알림도 있었던가요..?
이 기능보다 크롤링 코드 서버에 올리는게 더 중요한 것 같은데 그거부터 해결해보는건 어떤지 ......

**Comment by semi-cloud** [comment]
> @semi-cloud
> 
> 저희가 검색 기능, 푸시 알림도 있었던가요..? 이 기능보다 크롤링 코드 서버에 올리는게 더 중요한 것 같은데 그거부터 해결해보는건 어떤지 ......

발표 기준 아니고 전시 기준으로 10월까지 넉넉하게 잡은 기능입니다! 
서버 올리는거는 같이 해야하는 줄 몰랐네욥 우선순위가 높은 것부터 하도록 하죠!!!

**Comment by jimin3263** [comment]
> > @semi-cloud
> > 저희가 검색 기능, 푸시 알림도 있었던가요..? 이 기능보다 크롤링 코드 서버에 올리는게 더 중요한 것 같은데 그거부터 해결해보는건 어떤지 ......
> 
> 발표 기준 아니고 전시 기준으로 10월까지 넉넉하게 잡은 기능입니다! 서버 올리는거는 같이 해야하는 줄 몰랐네욥 우선순위가 높은 것부터 하도록 하죠!!!

크롤링 관련해서는 저희 세 명이 같이 하자고 하고 시작한거 아니었나요 ?ㅠㅠ 그래서 작은 기능이어도 사이트 별로 인원 나눠서 진행했구요.. 
다만 아무도 신경 안쓰길래 제가 잡고 있었던 거지 제 담당은 아니었습니다.. (물론 저도 신경크게 쓰던 부분은 아니었어서 크게 할말은 없어요 🥲)

오늘 회의에서 크롤링 관련해서는 확실히 역할을 나누고 가는게 좋을 것 같아요. 현재 3명이 맡은 기능은 끝낸 상황이고, 발표까지 새로운 api를 추가해서 클라에 적용하는 것은 힘들 것으로 보이니 발표까지 이 부분을 해결하도록 해요!

**Comment by semi-cloud** [comment]
> > > @semi-cloud
> > > 저희가 검색 기능, 푸시 알림도 있었던가요..? 이 기능보다 크롤링 코드 서버에 올리는게 더 중요한 것 같은데 그거부터 해결해보는건 어떤지 ......
> > 
> > 
> > 발표 기준 아니고 전시 기준으로 10월까지 넉넉하게 잡은 기능입니다! 서버 올리는거는 같이 해야하는 줄 몰랐네욥 우선순위가 높은 것부터 하도록 하죠!!!
> 
> 크롤링 관련해서는 저희 세 명이 같이 하자고 하고 시작한거 아니었나요 ?ㅠㅠ 그래서 작은 기능이어도 사이트 별로 인원 나눠서 진행했구요.. 다만 아무도 신경 안쓰길래 제가 잡고 있었던 거지 제 담당은 아니었습니다.. (물론 저도 신경크게 쓰던 부분은 아니었어서 크게 할말은 없어요 🥲)
> 
> 오늘 회의에서 크롤링 관련해서는 확실히 역할을 나누고 가는게 좋을 것 같아요. 현재 3명이 맡은 기능은 끝낸 상황이고, 발표까지 새로운 api를 추가해서 클라에 적용하는 것은 힘들 것으로 보이니 발표까지 이 부분을 해결하도록 해요!

저도 그런걸로 알고 있었는데 지민님 이슈 안에 들어가있길래 착각했네요 넵~!

**Comment by jimin3263** [comment]
우선순위 높은 기능부터 구현 하도록 얘기가 되어서 이 이슈는 잠시 닫아두겠습니다!
