### ISSUE TITLE
[백엔드] 팟 참여 예외 추가

### ISSUE THREAD

**Issue by jimin3263** [ticket-together/ticket-server#160]
# 기능 설명
- [ ] 팟 참여시 close된 팟이라면 들어가지 못하도록 
   - 모집 인원이 차더라도 마감되지 않도록

**Comment by jimin3263** [comment]
@younghyun-na 
제가 파악한 것은 일단 이건데 처리해야할 예외 상황이 더 있다면 작성해주세요 ~!

**Comment by younghyun-na** [comment]
옙 이 부분은 예외처리할 부분 더 있나 한번 고민해보겠습니당-!

**Comment by jimin3263** [comment]
> 옙 이 부분은 예외처리할 부분 더 있나 한번 고민해보겠습니당-!

혹시 팟 나갈 때 마감 후에 못나가게 하는거 어떤가욥 ? 
추가적으로 PR 확인 부탁드립니다 ~~!

**Comment by younghyun-na** [comment]
> 혹시 팟 나갈 때 마감 후에 못나가게 하는거 어떤가욥 ? 추가적으로 PR 확인 부탁드립니다 ~~!

이 부분도 추가하면 좋을 것 같네용! 참고하겠습니당-!
