### ISSUE TITLE
[백엔드] 테스트 id -> 현재 로그인한 회원으로 수정하도록

### ISSUE THREAD

**Issue by jimin3263** [ticket-together/ticket-server#174]
# 기능 설명
- [x] 테스트 id -> 현재 로그인한 회원으로 수정하도록

저희 api 수정해야 하네요 !!! 회의 이후 충분한 테스트가 끝난 부분은 바꾸도록 합시당 !

**Comment by jimin3263** [comment]
@younghyun-na

**Comment by younghyun-na** [comment]
예압 알겠습니당~~~!
