### ISSUE TITLE
[백엔드] 공연 정보 크롤링

### ISSUE THREAD

**Issue by jimin3263** [ticket-together/ticket-server#49]
# 기능 설명
- [x] 멜론 티켓에서 콘서트, 클래식 부분 크롤링
- [x] DB 넣기

**Comment by jimin3263** [comment]
@younghyun-na 

회의할 때 hall은 테이블 뺄 필요 없다고 결론나서 culture 테이블에 필드로 추가했어! 근데 키워드(콘서트, 클래식 등등) 이거를 굳이 테이블로 빼놓을 필요가 있을까 싶어서 고민중입니다.. 의견 부탁부탁

```
create table culture (
   culture_id bigint not null AUTO_INCREMENT,
    end_date datetime(6),
    start_date datetime(6),
    keyword varchar(255),
    img_url text,
    name varchar(255),
    hall_name varchar(255),
    primary key (culture_id)
);
```
일단 현재 테이블은 이거 입니당!

**Comment by younghyun-na** [comment]
키워드도 테이블로 만들 필요 없을 것 같아용! 필드에 어차피 category_name밖에 없으니까 culture 테이블에 넣을까욥?

**Comment by semi-cloud** [comment]
저 키워드가 회원가입할때 받는 키워드 맞나용??

**Comment by jimin3263** [comment]
넵넵 일단 CONCERT, CLASSIC 해서 디비에 넣어뒀슴다

**Comment by jimin3263** [comment]
> 저 키워드가 회원가입할때 받는 키워드 맞나용??

넵넵 일단 CONCERT, CLASSIC 해서 디비에 넣어뒀슴다

**Comment by jimin3263** [comment]
> 키워드도 테이블로 만들 필요 없을 것 같아용! 필드에 어차피 category_name밖에 없으니까 culture 테이블에 넣을까욥?

조아여!!!

**Comment by semi-cloud** [comment]
사용자 마이페이지에서 키워드가 보여야 하니까, 멤버 엔티티도 키워드가 필요할것 같은데 culture 테이블에만 넣으면 안되지 않을까요..!?ㅠㅠ

**Comment by semi-cloud** [comment]
현재 상태는 Member 와 Keyword 엔티티 다대다 관계를 MemberKeyword 엔티티 만들어서 풀어놓은 상태입니다앙

**Comment by jimin3263** [comment]
> 사용자 마이페이지에서 키워드가 보여야 하니까, 멤버 엔티티도 키워드가 필요할것 같은데 culture 테이블에만 넣으면 안되지 않을까요..!?ㅠㅠ

keyword 엔티티를 없애고 관계 테이블에 멤버 아이디랑 키워드 (enum) 저장하는 하는건요..?
culture는 사실상 키워드가 1대1 관계라서 테이블을 뺄 필요는 없는 것 같습니당

**Comment by semi-cloud** [comment]
오호 좋은 생각이네요 알겠습니다! 수정 반영해서 올리겠습니당
