### ISSUE TITLE
[백엔드] 리뷰 공연장 검색 쿼리 변경

### ISSUE THREAD

**Issue by younghyun-na** [ticket-together/ticket-server#69]
# 기능 설명
- [x] 현재 공연장 정보와 연결된 검색 기능을 검색 결과 내에서의 필터링으로 변경
- [x] hallId가 아닌 공연장 이름으로 검색 쿼리 변경

**Comment by younghyun-na** [comment]
@jimin3263 @semi-cloud 
공연장이름말고 기존에 hallId로 공연장을 구분했던 것을 cultureId로 구분하는 것도 괜찮을 것 같아서 논의에 올려봐용! 같은 공연장이라도 공연에 따라서 매번 좌석이 달라지기 때문에, 결국 공연에 따라 리뷰가 필터링되어야하는 것이라 cultureId로 구분해도 될 것 같은데 혹시 다들 이 방법에 대해선 어떻게 생각하시나욥?  
현재 api는 `/reviews/:hallId/add`  이러한데  `/reviews/:cultureId/add` 이렇게 바꾸는 방법이요!

**Comment by jimin3263** [comment]
> @jimin3263 @semi-cloud 공연장이름말고 기존에 hallId로 공연장을 구분했던 것을 cultureId로 구분하는 것도 괜찮을 것 같아서 논의에 올려봐용! 같은 공연장이라도 공연에 따라서 매번 좌석이 달라지기 때문에, 결국 공연에 따라 리뷰가 필터링되어야하는 것이라 cultureId로 구분해도 될 것 같은데 혹시 다들 이 방법에 대해선 어떻게 생각하시나욥? 현재 api는 `/reviews/:hallId/add` 이러한데 `/reviews/:cultureId/add` 이렇게 바꾸는 방법이요!

culture가 계속 있는 데이터가 아니라 짧은 주기(아직 업데이트 기한 관련 논의하진 않았지만.. 하루 혹은 길어봤자 일주일)로 삭제되는 데이터라 애매하다고 생각합니당..

**Comment by semi-cloud** [comment]
> @jimin3263 @semi-cloud
> 공연장이름말고 기존에 hallId로 공연장을 구분했던 것을 cultureId로 구분하는 것도 괜찮을 것 같아서 논의에 올려봐용! 같은 공연장이라도 공연에 따라서 매번 좌석이 달라지기 때문에, 결국 공연에 따라 리뷰가 필터링되어야하는 것이라 cultureId로 구분해도 될 것 같은데 혹시 다들 이 방법에 대해선 어떻게 생각하시나욥?
> 현재 api는 `/reviews/:hallId/add` 이러한데 `/reviews/:cultureId/add` 이렇게 바꾸는 방법이요!

저도 위에 의견에 동의합니다..🥲

**Comment by younghyun-na** [comment]
공연장 상세정보에서 해당 공연장 리뷰로 넘어갈 때 공연장 이름 정보가 들어와야하는데 culture나 hall을 이용해서 공연장을 식별하는 데이터를 저장할 수 없으면 이 기능이 불가능할 것 같아서,, 그럼 이 부분은 어떻게 처리해야할까용..?😢

**Comment by jimin3263** [comment]
> 공연장 상세정보에서 해당 공연장 리뷰로 넘어갈 때 공연장 이름 정보가 들어와야하는데 culture나 hall을 이용해서 공연장을 식별하는 데이터를 저장할 수 없으면 이 기능이 불가능할 것 같아서,, 그럼 이 부분은 어떻게 처리해야할까용..?😢

쿼리 스트링으로 공연장 이름..?
