### ISSUE TITLE
[백엔드] STOMP 프로토콜을 이용하여 실시간 채팅 변경

### ISSUE THREAD

**Issue by semi-cloud** [ticket-together/ticket-server#81]
# 리팩토링 내용
- [x]  Spring Websocket STOMP 사용하여 `pub` / `sub` 방식으로 채팅 방식 변경
  - [x] 채팅방 생성
  - [x] 채팅방 입장
  - [x] 채팅 메시지 보내기
  - [x]  채팅 목록 조회

**Comment by jimin3263** [comment]
왜 엄청난 변경을 하고 있는거죳 ?! 진행하다 문제가 생긴건가요...?🥹

**Comment by semi-cloud** [comment]
> 왜 엄청난 변경을 하고 있는거죳 ?! 진행하다 문제가 생긴건가요...?🥹

앗 이제 봤네요 아뇨!! 문제가 생긴거는 아니고 단체 채팅방에 좀 더 나은 방식으로 변경했습니당
