### ISSUE TITLE
[백엔드] docker 이용해 Rabbit MQ 서버 세팅

### ISSUE THREAD

**Issue by jimin3263** [ticket-together/ticket-server#94]
# 기능 설명
- [x] 새 계정 생성 및 vhost 설정
- [x] 도커 Rabbit MQ 설치
  - [x] 플러그인 설치

> 기본 계정인 guest/guest는 RabbitMQ가 로컬 호스트에 있는 경우만 접근 가능

**Comment by semi-cloud** [comment]
### RabbitMQ 계정 생성 및 Vhost 설정
```java
rabbitmqctl add_user [ID] [PASSWORD]  // 계정 생성
rabbitmqctl set_user_tags [ID] administrator // 관리자로 등록
rabbitmqctl set_permissions -p / [ID] ".*" ".*" ".*" //모든 권한 등록
```

**Comment by jimin3263** [comment]
> ### RabbitMQ 계정 생성 및 Vhost 설정
> ```java
> rabbitmqctl add_user [ID] [PASSWORD]  // 계정 생성
> rabbitmqctl set_user_tags [ID] administrator // 관리자로 등록
> rabbitmqctl set_permissions -p / [ID] ".*" ".*" ".*" //모든 권한 등록
> ```

계정 생성해서 디스코드에 계정 정보 업로드 완료했씁니다 ~🙌
