### ISSUE TITLE
[백엔드] chat room 엔티티 수정

### ISSUE THREAD

**Issue by jimin3263** [ticket-together/ticket-server#97]
# 기능 설명
- [x] chat room 엔티티에서 pot_id -> parts_id 로 수정
- [x] `@OneToOne`으로 팟과 연결

**Comment by jimin3263** [comment]
@semi-cloud 
확인부탁드립니당

**Comment by semi-cloud** [comment]
> @semi-cloud
> 확인부탁드립니당

넵 ~! 수정해서 올리겠습니다
